"""Full FC Mobile player pool — 800 names imported from EA FC Mobile master list."""

FC_MOBILE_FULL_POOL = [
    ('Mohamed Salah', "Active star"),
    ('Ousmane Dembélé', "Active star"),
    ('Rodri', "Active star"),
    ('Virgil van Dijk', "Active star"),
    ('Jude Bellingham', "Active star"),
    ('Erling Haaland', "Active star"),
    ('Raphinha', "Active star"),
    ('Achraf Hakimi', "Active star"),
    ('Lamine Yamal', "Active star"),
    ('Vitinha', "Active star"),
    ('Gianluigi Donnarumma', "Active star"),
    ('Pedri', "Active star"),
    ('Joshua Kimmich', "Active star"),
    ('Alisson', "Active star"),
    ('Harry Kane', "Active star"),
    ('Federico Valverde', "Active star"),
    ('Vini Jr.', "Active star"),
    ('Florian Wirtz', "Active star"),
    ('Thibaut Courtois', "Active star"),
    ('Robert Lewandowski', "Active star"),
    ('Lautaro Martínez', "Active star"),
    ('Alexander Isak', "Active star"),
    ('Jamal Musiala', "Active star"),
    ('Gabriel', "Active star"),
    ('Bukayo Saka', "Active star"),
    ('Jan Oblak', "Active star"),
    ('Cole Palmer', "Active star"),
    ('Khvicha Kvaratskhelia', "Active star"),
    ('Alessandro Bastoni', "Active star"),
    ('Serhou Guirassy', "Active star"),
    ('Kevin De Bruyne', "Active star"),
    ('Frenkie de Jong', "Active star"),
    ('Moisés Caicedo', "Active star"),
    ('Declan Rice', "Active star"),
    ('Marquinhos', "Active star"),
    ('Yann Sommer', "Active star"),
    ('Jules Koundé', "Active star"),
    ('Bruno Fernandes', "Active star"),
    ('William Saliba', "Active star"),
    ('Julián Alvarez', "Active star"),
    ('Jonathan Tah', "Active star"),
    ('Alexis Mac Allister', "Active star"),
    ('Mike Maignan', "Active star"),
    ('Martin Ødegaard', "Active star"),
    ('David Raya', "Active star"),
    ('Viktor Gyökeres', "Active star"),
    ('Nicolò Barella', "Active star"),
    ('Victor Osimhen', "Active star"),
    ('Nuno Mendes', "Active star"),
    ('Antonio Rüdiger', "Active star"),
    ('Michael Olise', "Active star"),
    ('Trent Alexander-Arnold', "Active star"),
    ('Rúben Dias', "Active star"),
    ('Paulo Dybala', "Active star"),
    ('Bruno Guimarães', "Active star"),
    ('Willian Pacho', "Active star"),
    ('Ibrahima Konaté', "Active star"),
    ('Hakan Çalhanoğlu', "Active star"),
    ('Sandro Tonali', "Active star"),
    ('Nico Williams', "Active star"),
    ('Tijjani Reijnders', "Active star"),
    ('Marc-André ter Stegen', "Active star"),
    ('Gregor Kobel', "Active star"),
    ('Ederson', "Active star"),
    ('Federico Dimarco', "Active star"),
    ('Scott McTominay', "Active star"),
    ('Ryan Gravenberch', "Active star"),
    ('Emiliano Martínez', "Active star"),
    ('João Neves', "Active star"),
    ('Antoine Griezmann', "Active star"),
    ('Bryan Mbeumo', "Active star"),
    ("N'Golo Kanté", "Active star"),
    ('Désiré Doué', "Active star"),
    ('Carvajal', "Active star"),
    ('Unai Simón', "Active star"),
    ('Marcus Thuram', "Active star"),
    ('Péter Gulácsi', "Active star"),
    ('Luis Díaz', "Active star"),
    ('De Gea', "Active star"),
    ('Nico Schlotterbeck', "Active star"),
    ('Heung Min Son', "Active star"),
    ('Phil Foden', "Active star"),
    ('Fabián Ruiz', "Active star"),
    ('Youri Tielemans', "Active star"),
    ('Granit Xhaka', "Active star"),
    ('Karim Benzema', "Active star"),
    ('Iñigo Martínez', "Active star"),
    ('Rodrygo', "Active star"),
    ('Dani Olmo', "Active star"),
    ('Dayot Upamecano', "Active star"),
    ('Patrik Schick', "Active star"),
    ('Bremer', "Active star"),
    ('Theo Hernández', "Active star"),
    ('Marcos Llorente', "Active star"),
    ('Rodrigo De Paul', "Active star"),
    ('João Cancelo', "Active star"),
    ('Sancet', "Active star"),
    ('Alphonso Davies', "Active star"),
    ('Jordan Pickford', "Active star"),
    ('Denzel Dumfries', "Active star"),
    ('Sergej Milinković-Savić', "Active star"),
    ('Joško Gvardiol', "Active star"),
    ('Aurélien Tchouaméni', "Active star"),
    ('Marc Cucurella', "Active star"),
    ('Grimaldo', "Active star"),
    ('Benjamin Pavard', "Active star"),
    ('Enzo Fernández', "Active star"),
    ('Wojciech Szczęsny', "Active star"),
    ('Álex Baena', "Active star"),
    ('Mattia Zaccagni', "Active star"),
    ('Giorgi Mamardashvili', "Active star"),
    ('Exequiel Palacios', "Active star"),
    ('Xavi Simons', "Active star"),
    ('Manuel Neuer', "Active star"),
    ('Rúben Neves', "Active star"),
    ('Cody Gakpo', "Active star"),
    ('Bernardo Silva', "Active star"),
    ('Manuel Locatelli', "Active star"),
    ('Christian Pulisic', "Active star"),
    ('Diogo Costa', "Active star"),
    ('Ollie Watkins', "Active star"),
    ('James Maddison', "Active star"),
    ('Marco Carnesecchi', "Active star"),
    ('Omar Marmoush', "Active star"),
    ('Rafael Leão', "Active star"),
    ('Éder Militão', "Active star"),
    ('Romelu Lukaku', "Active star"),
    ('Isco', "Active star"),
    ('Bradley Barcola', "Active star"),
    ('Moussa Diaby', "Active star"),
    ('Vivian', "Active star"),
    ('Ademola Lookman', "Active star"),
    ('Riyad Mahrez', "Active star"),
    ('Alexander Sørloth', "Active star"),
    ('Francesco Acerbi', "Active star"),
    ('Stefan de Vrij', "Active star"),
    ('Willi Orban', "Active star"),
    ('Adrien Rabiot', "Active star"),
    ('Eduardo Camavinga', "Active star"),
    ('Dominik Szoboszlai', "Active star"),
    ('Henrikh Mkhitaryan', "Active star"),
    ('Lucas Torreira', "Active star"),
    ('Giovanni Di Lorenzo', "Active star"),
    ('Morten Hjulmand', "Active star"),
    ('Dejan Kulusevski', "Active star"),
    ('Mikel Merino', "Active star"),
    ('Ayoze', "Active star"),
    ('Iñaki Williams', "Active star"),
    ('Pedro Gonçalves', "Active star"),
    ('Joan García', "Active star"),
    ('Álex Remiro', "Active star"),
    ('Dávid Hancko', "Active star"),
    ('Anthony Gordon', "Active star"),
    ('Lucas Chevalier', "Active star"),
    ('Mateo Kovačić', "Active star"),
    ('Aleix García', "Active star"),
    ('Thomas Partey', "Active star"),
    ('Stanislav Lobotka', "Active star"),
    ('Jeremie Frimpong', "Active star"),
    ('Luka Modrić', "Active star"),
    ('Sadio Mané', "Active star"),
    ('Oliver Baumann', "Active star"),
    ('Matheus Cunha', "Active star"),
    ('Zubimendi', "Active star"),
    ('Matz Sels', "Active star"),
    ('Gavi', "Active star"),
    ('Eberechi Eze', "Active star"),
    ('Balde', "Active star"),
    ('İlkay Gündoğan', "Active star"),
    ('Loïs Openda', "Active star"),
    ('Palhinha', "Active star"),
    ('Julian Brandt', "Active star"),
    ('Jarrod Bowen', "Active star"),
    ('Murillo', "Active star"),
    ('Boubacar Kamara', "Active star"),
    ('Nathan Aké', "Active star"),
    ('Ferran Torres', "Active star"),
    ('Angelo Stiller', "Active star"),
    ('Piero Hincapié', "Active star"),
    ('Artem Dovbyk', "Active star"),
    ('Hugo Ekitiké', "Active star"),
    ('Iago Aspas', "Active star"),
    ('Moise Kean', "Active star"),
    ('Ronald Araujo', "Active star"),
    ('Kingsley Coman', "Active star"),
    ('Leandro Trossard', "Active star"),
    ('Benjamin White', "Active star"),
    ('Mateo Retegui', "Active star"),
    ('José María Giménez', "Active star"),
    ('Gianluca Mancini', "Active star"),
    ('Amir Rrahmani', "Active star"),
    ('Nikola Milenković', "Active star"),
    ('Robin Le Normand', "Active star"),
    ('Leon Goretzka', "Active star"),
    ('Joelinton', "Active star"),
    ('Felix Nmecha', "Active star"),
    ('André-Franck Zambo Anguissa', "Active star"),
    ('Éderson', "Active star"),
    ('Emre Can', "Active star"),
    ('Orkun Kökçü', "Active star"),
    ('Pedro Porro', "Active star"),
    ('Denis Zakaria', "Active star"),
    ('Morgan Rogers', "Active star"),
    ('Mile Svilar', "Active star"),
    ('Malik Tillman', "Active star"),
    ('Otávio', "Active star"),
    ('Salem Al Dawsari', "Active star"),
    ('Konrad Laimer', "Active star"),
    ('Mattéo Guendouzi', "Active star"),
    ('Álex Berenguer', "Active star"),
    ('David Raum', "Active star"),
    ('David Alaba', "Active star"),
    ('Gerónimo Rulli', "Active star"),
    ('Milos Kerkez', "Active star"),
    ('Guglielmo Vicario', "Active star"),
    ('Giovani Lo Celso', "Active star"),
    ('Ivan Provedel', "Active star"),
    ('Morgan Gibbs-White', "Active star"),
    ('Maximilian Mittelstädt', "Active star"),
    ('Pablo Barrios', "Active star"),
    ('Koen Casteels', "Active star"),
    ('Alex Meret', "Active star"),
    ('Andrew Robertson', "Active star"),
    ('Davinson Sánchez', "Active star"),
    ('Malcom', "Active star"),
    ('Yassine Bounou', "Active star"),
    ('Antonee Robinson', "Active star"),
    ('Kaoru Mitoma', "Active star"),
    ('Vangelis Pavlidis', "Active star"),
    ('Fabinho', "Active star"),
    ('Riccardo Orsolini', "Active star"),
    ('Micky van de Ven', "Active star"),
    ('Leroy Sané', "Active star"),
    ('Ezri Konsa', "Active star"),
    ('Charles De Ketelaere', "Active star"),
    ('Jurriën Timber', "Active star"),
    ('Trincão', "Active star"),
    ('Serge Gnabry', "Active star"),
    ('Jonathan Burkardt', "Active star"),
    ('Fabian Schär', "Active star"),
    ('Pierre-Emile Højbjerg', "Active star"),
    ('Kai Havertz', "Active star"),
    ('Dean Huijsen', "Active star"),
    ('Rafa', "Active star"),
    ('Oyarzabal', "Active star"),
    ('Takefusa Kubo', "Active star"),
    ('Ángel Di María', "Active star"),
    ('Mario Götze', "Active star"),
    ('Domenico Berardi', "Active star"),
    ('Jean-Philippe Mateta', "Active star"),
    ('John Stones', "Active star"),
    ('Manuel Akanji', "Active star"),
    ('Jonathan David', "Active star"),
    ('Mason Greenwood', "Active star"),
    ('Parejo', "Active star"),
    ('Dodi Lukébakio', "Active star"),
    ('Ritsu Doan', "Active star"),
    ('Yoane Wissa', "Active star"),
    ('Dušan Vlahović', "Active star"),
    ('Waldemar Anton', "Active star"),
    ('Matthijs de Ligt', "Active star"),
    ('Kalidou Koulibaly', "Active star"),
    ('Youssef En-Nesyri', "Active star"),
    ('Pau Cubarsí', "Active star"),
    ('Duván Zapata', "Active star"),
    ('Nicolás Otamendi', "Active star"),
    ('Marc Guéhi', "Active star"),
    ('Nacho Fernández', "Active star"),
    ('Matthias Ginter', "Active star"),
    ('Brahim', "Active star"),
    ('Alessandro Buongiorno', "Active star"),
    ('Aymeric Laporte', "Active star"),
    ('Cristian Romero', "Active star"),
    ('Savinho', "Active star"),
    ('Robin Koch', "Active star"),
    ('Ante Budimir', "Active star"),
    ('Chris Wood', "Active star"),
    ('Ibañez', "Active star"),
    ('Kim Min Jae', "Active star"),
    ('Alessio Romagnoli', "Active star"),
    ('Sven Botman', "Active star"),
    ('Khéphren Thuram', "Active star"),
    ('Conor Gallagher', "Active star"),
    ('Reece James', "Active star"),
    ('Filip Kostić', "Active star"),
    ('Sergi Darder', "Active star"),
    ('John McGinn', "Active star"),
    ('Davide Frattesi', "Active star"),
    ('Michele Di Gregorio', "Active star"),
    ('Carlos Augusto', "Active star"),
    ('Miguel Gutiérrez', "Active star"),
    ('Ferland Mendy', "Active star"),
    ('Teun Koopmeiners', "Active star"),
    ('Ivan Perišić', "Active star"),
    ('Yangel Herrera', "Active star"),
    ('Carlos Baleba', "Active star"),
    ('Corentin Tolisso', "Active star"),
    ('Yannick Carrasco', "Active star"),
    ('Dean Henderson', "Active star"),
    ('Daniel Muñoz', "Active star"),
    ('Marten de Roon', "Active star"),
    ('Marcelo Brozović', "Active star"),
    ('Brais Méndez', "Active star"),
    ('Johnny Cardoso', "Active star"),
    ('Alexander Nübel', "Active star"),
    ('Jacob Murphy', "Active star"),
    ('Koke', "Active star"),
    ('Robert Andrich', "Active star"),
    ('Youssouf Fofana', "Active star"),
    ('Rayan Aït-Nouri', "Active star"),
    ('Gayà', "Active star"),
    ('Gabriel Martinelli', "Active star"),
    ('Giuliano Simeone', "Active star"),
    ('Kevin Trapp', "Active star"),
    ('Anderson Talisca', "Active star"),
    ('Nadiem Amiri', "Active star"),
    ('Nick Pope', "Active star"),
    ('Ivan Toney', "Active star"),
    ('David Soria', "Active star"),
    ('Federico Chiesa', "Active star"),
    ('Lisandro Martínez', "Active star"),
    ('Galeno', "Active star"),
    ('Andriy Lunin', "Active star"),
    ('Antony', "Active star"),
    ('Matteo Darmian', "Active star"),
    ('Matteo Politano', "Active star"),
    ('Lucas Perri', "Active star"),
    ('Remo Freuler', "Active star"),
    ('Ricardo Horta', "Active star"),
    ('Gerard Moreno', "Active star"),
    ('Rui Silva', "Active star"),
    ('Dani Ceballos', "Active star"),
    ('Edmond Tapsoba', "Active star"),
    ('Karim Adeyemi', "Active star"),
    ('Anthony Elanga', "Active star"),
    ('Lukáš Hrádecký', "Active star"),
    ('David Neres', "Active star"),
    ('Evan Ndicka', "Active star"),
    ('Isi', "Active star"),
    ('Wladimiro Falcone', "Active star"),
    ('Lucas Hernández', "Active star"),
    ('Randal Kolo Muani', "Active star"),
    ('Morata', "Active star"),
    ('Gonçalo Inácio', "Active star"),
    ('Leonardo Balerdi', "Active star"),
    ('Andrej Kramarić', "Active star"),
    ('Christopher Nkunku', "Active star"),
    ('Mohamed Simakan', "Active star"),
    ('Danilo Pereira', "Active star"),
    ('Arda Güler', "Active star"),
    ('Pierre-Emerick Aubameyang', "Active star"),
    ('Tim Kleindienst', "Active star"),
    ('Simon Banza', "Active star"),
    ('Nayef Aguerd', "Active star"),
    ('Victor Boniface', "Active star"),
    ('Mauro Icardi', "Active star"),
    ('Fikayo Tomori', "Active star"),
    ('Niklas Süle', "Active star"),
    ('Rayan Cherki', "Active star"),
    ('Edin Džeko', "Active star"),
    ('Milan Škriniar', "Active star"),
    ('Raíllo', "Active star"),
    ('Barış Alper Yılmaz', "Active star"),
    ('Ruben Loftus-Cheek', "Active star"),
    ('Franck Yannick Kessié', "Active star"),
    ('Quinten Timber', "Active star"),
    ('Marcel Sabitzer', "Active star"),
    ('André Onana', "Active star"),
    ('Fredrik Aursnes', "Active star"),
    ('Ismaël Bennacer', "Active star"),
    ('Fred', "Active star"),
    ('Lorenzo Pellegrini', "Active star"),
    ('Maxim De Cuyper', "Active star"),
    ('Destiny Udogie', "Active star"),
    ('Mohammed Kudus', "Active star"),
    ('Álvaro Carreras', "Active star"),
    ('Gabriel Sara', "Active star"),
    ('Warren Zaïre-Emery', "Active star"),
    ('Mauro Arambarri', "Active star"),
    ('Curtis Jones', "Active star"),
    ('Elliot Anderson', "Active star"),
    ('Lucas Paquetá', "Active star"),
    ('Mingueza', "Active star"),
    ('Andrey Santos', "Active star"),
    ('Brice Samba', "Active star"),
    ('Ola Aina', "Active star"),
    ('Jonathan Clauss', "Active star"),
    ('Bernd Leno', "Active star"),
    ('Robin Gosens', "Active star"),
    ('Douglas Luiz', "Active star"),
    ('Georgiy Sudakov', "Active star"),
    ('Raphaël Guerreiro', "Active star"),
    ('Mario Pašalić', "Active star"),
    ('Noussair Mazraoui', "Active star"),
    ('Dominik Livaković', "Active star"),
    ('Wilfried Singo', "Active star"),
    ('Uğurcan Çakır', "Active star"),
    ('Xaver Schlager', "Active star"),
    ('Lucas Digne', "Active star"),
    ('Piotr Zieliński', "Active star"),
    ('Kieran Trippier', "Active star"),
    ('Ruiz de Galarreta', "Active star"),
    ('Anatoliy Trubin', "Active star"),
    ('Ellyes Skhiri', "Active star"),
    ('Rodrigo Bentancur', "Active star"),
    ('Bryan Cristante', "Active star"),
    ('Javi Galán', "Active star"),
    ('Alex Iwobi', "Active star"),
    ('Mikkel Damsgaard', "Active star"),
    ('Lewis Hall', "Active star"),
    ('Frederik Rønnow', "Active star"),
    ('Mohamed Amoura', "Active star"),
    ('Bento', "Active star"),
    ('Franck Honorat', "Active star"),
    ('Julian Quiñones', "Active star"),
    ('Pascal Groß', "Active star"),
    ('Noni Madueke', "Active star"),
    ('Jack Grealish', "Active star"),
    ('Benjamin Henrichs', "Active star"),
    ('Tino Livramento', "Active star"),
    ('Noa Lang', "Active star"),
    ('Benjamin Šeško', "Active star"),
    ('Đorđe Petrović', "Active star"),
    ('Pedro Neto', "Active star"),
    ('Antoine Semenyo', "Active star"),
    ('Benjamin André', "Active star"),
    ('Steven Bergwijn', "Active star"),
    ('Gabriel Jesus', "Active star"),
    ('Harvey Barnes', "Active star"),
    ('Aaron Wan-Bissaka', "Active star"),
    ('Pierre Kalulu', "Active star"),
    ('Valentin Castellanos', "Active star"),
    ('Nicolas Pépé', "Active star"),
    ('Boulaye Dia', "Active star"),
    ('Mario Hermoso', "Active star"),
    ('Édouard Mendy', "Active star"),
    ('Ermedin Demirović', "Active star"),
    ('Predrag Rajković', "Active star"),
    ('Ayoub El Kaabi', "Active star"),
    ('Nicolas Jackson', "Active star"),
    ('Hans Vanaken', "Active star"),
    ('Fermín', "Active star"),
    ('Marcus Rashford', "Active star"),
    ('Christos Tzolis', "Active star"),
    ('Konstantinos Fortounis', "Active star"),
    ('Jérémy Doku', "Active star"),
    ('Igor Paixão', "Active star"),
    ('Jerdy Schouten', "Active star"),
    ('Gonçalo Ramos', "Active star"),
    ('Dominic Solanke', "Active star"),
    ('Thomas Müller', "Active star"),
    ('Vincenzo Grifo', "Active star"),
    ('Armand Laurienté', "Active star"),
    ('Christian Nørgaard', "Active star"),
    ('Levi Colwill', "Active star"),
    ('Maghnes Akliouche', "Active star"),
    ('Marco Asensio', "Active star"),
    ('Kerem Aktürkoğlu', "Active star"),
    ('Jan Paul van Hecke', "Active star"),
    ('Álvaro García', "Active star"),
    ('Deniz Undav', "Active star"),
    ('Samuel Chukwueze', "Active star"),
    ('Castello Lukeba', "Active star"),
    ('Casemiro', "Active star"),
    ('Evanilson', "Active star"),
    ('Abdülkerim Bardakcı', "Active star"),
    ('Arthur Theate', "Active star"),
    ('Jadon Sancho', "Active star"),
    ('Pau Torres', "Active star"),
    ('Riqui Puig', "Active star"),
    ('Borja Iglesias', "Active star"),
    ('Odilon Kossounou', "Active star"),
    ('Florentino', "Active star"),
    ('Yeremy Pino', "Active star"),
    ('Sergio Busquets', "Active star"),
    ('Federico Gatti', "Active star"),
    ('Diego Llorente', "Active star"),
    ('Ousmane Diomande', "Active star"),
    ('Clément Lenglet', "Active star"),
    ('Harry Maguire', "Active star"),
    ('Alexsandro', "Active star"),
    ('Andreas Christensen', "Active star"),
    ('James Tarkowski', "Active star"),
    ('Chris Smalling', "Active star"),
    ('Richard Ríos', "Active star"),
    ('Callum McGregor', "Active star"),
    ('Daizen Maeda', "Active star"),
    ('Kouadio Manu Koné', "Active star"),
    ('Rodrigo Zalazar', "Active star"),
    ('Matheus Nunes', "Active star"),
    ('Mario Lemina', "Active star"),
    ('Nuno Santos', "Active star"),
    ('Yuri Berchiche', "Active star"),
    ('Diogo Dalot', "Active star"),
    ('Stefan Ortega', "Active star"),
    ('Paulo Gazzaniga', "Active star"),
    ('Kyle Walker', "Active star"),
    ('Rodinei', "Active star"),
    ('Andrei Rațiu', "Active star"),
    ('Maximilian Arnold', "Active star"),
    ('Sergiño Dest', "Active star"),
    ('Andrea Cambiaso', "Active star"),
    ('Davide Zappacosta', "Active star"),
    ('Ramy Bensebaini', "Active star"),
    ('Ferdi Kadıoğlu', "Active star"),
    ('Hidemasa Morita', "Active star"),
    ('Darwin Núñez', "Active star"),
    ('Luis Milla', "Active star"),
    ('Nico González', "Active star"),
    ('Ryan Christie', "Active star"),
    ('Pablo Fornals', "Active star"),
    ('Nahuel Molina', "Active star"),
    ('Ian Maatsen', "Active star"),
    ('Konstantinos Tzolakis', "Active star"),
    ('Angeliño', "Active star"),
    ('Vanja Milinković-Savić', "Active star"),
    ('Julian Ryerson', "Active star"),
    ('Evander', "Active star"),
    ('Anton Stach', "Active star"),
    ('Jordan Henderson', "Active star"),
    ('Marcos Alonso', "Active star"),
    ('Paul Pogba', "Active star"),
    ('Sergio Gómez', "Active star"),
    ('Dan Ndoye', "Active star"),
    ('Pape Matar Sarr', "Active star"),
    ('Nicolò Rovella', "Active star"),
    ('Amadou Onana', "Active star"),
    ('Jasper Cillessen', "Active star"),
    ('Hamari Traoré', "Active star"),
    ('Pau López', "Active star"),
    ('Matty Cash', "Active star"),
    ('Mauro Júnior', "Active star"),
    ('Ismael Saibari', "Active star"),
    ('Alexandr Golovin', "Active star"),
    ('Kasper Schmeichel', "Active star"),
    ('Juan Musso', "Active star"),
    ('Sergio Herrera', "Active star"),
    ('Rasmus Kristensen', "Active star"),
    ('Mario Gila', "Active star"),
    ('Łukasz Skorupski', "Active star"),
    ('Kepa', "Active star"),
    ('Tyler Adams', "Active star"),
    ('Nicolás Domínguez', "Active star"),
    ('Pervis Estupiñán', "Active star"),
    ('Álvaro Valles', "Active star"),
    ('Alan Varela', "Active star"),
    ('Lewis Cook', "Active star"),
    ('Nikola Vlašić', "Active star"),
    ('Sergi Cardona', "Active star"),
    ('Valentin Rongier', "Active star"),
    ('Denis Bouanga', "Active star"),
    ('Kamil Grabara', "Active star"),
    ('Reinildo', "Active star"),
    ('Caoimhin Kelleher', "Active star"),
    ('Alexis Saelemaekers', "Active star"),
    ('Kaku', "Active star"),
    ('Amine Gouiri', "Active star"),
    ('Luke Shaw', "Active star"),
    ('Augusto Batalla', "Active star"),
    ('Marko Dmitrović', "Active star"),
    ('Guruzeta', "Active star"),
    ('Fran García', "Active star"),
    ('Aleksandar Pavlović', "Active star"),
    ('Malo Gusto', "Active star"),
    ('Manuel Ugarte', "Active star"),
    ('Arnau Martínez', "Active star"),
    ('Kaishū Sano', "Active star"),
    ('Marko Livaja', "Active star"),
    ('Wataru Endo', "Active star"),
    ('Adam Wharton', "Active star"),
    ('Fernando Muslera', "Active star"),
    ('Albert Guðmundsson', "Active star"),
    ('João Félix', "Active star"),
    ('Moleiro', "Active star"),
    ('Walter Benítez', "Active star"),
    ('Olivier Boscagli', "Active star"),
    ('Sander Berge', "Active star"),
    ('Thiago Almada', "Active star"),
    ('Evann Guessand', "Active star"),
    ('Lee Kang In', "Active star"),
    ('Amad', "Active star"),
    ('Nico Paz', "Active star"),
    ('Sead Kolašinac', "Active star"),
    ('Stole Dimitrievski', "Active star"),
    ('Justin Kluivert', "Active star"),
    ('Lucas Zelarayán', "Active star"),
    ('Stephan El Shaarawy', "Active star"),
    ('Donyell Malen', "Active star"),
    ('Ismaïla Sarr', "Active star"),
    ('Facundo Medina', "Active star"),
    ('Santiago Giménez', "Active star"),
    ('Joey Veerman', "Active star"),
    ('Kenan Yıldız', "Active star"),
    ('Marc Bartra', "Active star"),
    ('Martin Terrier', "Active star"),
    ('Alexandre Lacazette', "Active star"),
    ('Hany Mukhtar', "Active star"),
    ('Stefan Posch', "Active star"),
    ('Maximilian Beier', "Active star"),
    ('Emmanuel Agbadou', "Active star"),
    ('Leon Bailey', "Active star"),
    ('Viktor Tsygankov', "Active star"),
    ('Iliman Ndiaye', "Active star"),
    ('Nordi Mukiele', "Active star"),
    ('Trevoh Chalobah', "Active star"),
    ('João Pedro', "Active star"),
    ('Marco Reus', "Active star"),
    ('Maxence Lacroix', "Active star"),
    ('Brennan Johnson', "Active star"),
    ('Juan Foyth', "Active star"),
    ('Marcin Bułka', "Active star"),
    ('Bafodé Diakité', "Active star"),
    ('Idrissa Gueye', "Active star"),
    ('Jhon Durán', "Active star"),
    ('Fábio Silva', "Active star"),
    ('Marc Casadó', "Active star"),
    ('Jordy Clasie', "Active star"),
    ('Eric Dier', "Active star"),
    ('Wesley Fofana', "Active star"),
    ('Eric García', "Active star"),
    ('Nick Woltemade', "Active star"),
    ('Niclas Füllkrug', "Active star"),
    ('Cameron Carter-Vickers', "Active star"),
    ('Edon Zhegrova', "Active star"),
    ('Illia Zabarnyi', "Active star"),
    ('Samu', "Active star"),
    ('Thilo Kehrer', "Active star"),
    ('Luis Suárez', "Active star"),
    ('Carles Gil', "Active star"),
    ('Francisco Conceição', "Active star"),
    ('Abderrazak Hamdallah', "Active star"),
    ('Joe Gomez', "Active star"),
    ('Emil Forsberg', "Active star"),
    ('Toluwalase Arokodare', "Active star"),
    ('Gianluca Scamacca', "Active star"),
    ('Olivier Giroud', "Active star"),
    ('Sebastián Coates', "Active star"),
    ('Arkadiusz Milik', "Active star"),
    ('Marcos Leonardo', "Active star"),
    ('Jarrad Branthwaite', "Active star"),
    ('Kevin Danso', "Active star"),
    ('Philipp Lienhart', "Active star"),
    ('Berat Djimsiti', "Active star"),
    ('Vedat Muriqi', "Active star"),
    ('Catena', "Active star"),
    ('Nathan Collins', "Active star"),
    ('Dan Burn', "Active star"),
    ('Weston McKennie', "Active star"),
    ('Alexander Bah', "Active star"),
    ('Marcos Acuña', "Active star"),
    ('Nuno Tavares', "Active star"),
    ('Ridle Baku', "Active star"),
    ('Lukáš Provod', "Active star"),
    ('Cameron Puertas', "Active star"),
    ('Lewis Ferguson', "Active star"),
    ('Georginio Wijnaldum', "Active star"),
    ('Jordi Alba', "Active star"),
    ('Mykola Shaparenko', "Active star"),
    ('Kenneth Taylor', "Active star"),
    ('Luka Sučić', "Active star"),
    ('Hugo Larsson', "Active star"),
    ('Robert Sánchez', "Active star"),
    ('Gonzalo Montiel', "Active star"),
    ('Santiago Ascacíbar', "Active star"),
    ('Mahdi Camara', "Active star"),
    ('Jacob Ramsey', "Active star"),
    ('Leonardo Spinazzola', "Active star"),
    ('Johan Mojica', "Active star"),
    ('Zubeldia', "Active star"),
    ('Bart Verbruggen', "Active star"),
    ('Mert Günok', "Active star"),
    ('Cristiano Biraghi', "Active star"),
    ('Luis Henrique', "Active star"),
    ('Jauregizar', "Active star"),
    ('Mattia Perin', "Active star"),
    ('Jens Stage', "Active star"),
    ("Matt O'Riley", "Active star"),
    ('Chiquinho', "Active star"),
    ('Renan Lodi', "Active star"),
    ('Mitchell Weiser', "Active star"),
    ('Marcelino Moreno', "Active star"),
    ('Myles Lewis-Skelly', "Active star"),
    ('Leandro Paredes', "Active star"),
    ('Adam Marušić', "Active star"),
    ('Dodô', "Active star"),
    ('Manuel Lazzari', "Active star"),
    ('Francisco Moura', "Active star"),
    ('Alistair Johnston', "Active star"),
    ('Geny Catamo', "Active star"),
    ('Yacine Adli', "Active star"),
    ('Andrea Colpani', "Active star"),
    ('Riccardo Calafiori', "Active star"),
    ('Geoffrey Kondogbia', "Active star"),
    ('Pape Gueye', "Active star"),
    ('Ladislav Krejčí', "Active star"),
    ('Daniel Bragança', "Active star"),
    ('Oscar Dorley', "Active star"),
    ('Alessandro Del Piero', "Iconic retired"),
    ('Alex Morgan', "Iconic retired"),
    ('Andrés Iniesta', "Iconic retired"),
    ('Bixente Lizarazu', "Iconic retired"),
    ('Bobby Moore', "Iconic retired"),
    ('Cafu', "Iconic retired"),
    ('Carlos Alberto', "Iconic retired"),
    ('Caroline Seger', "Iconic retired"),
    ('Cha Bum-Kun', "Iconic retired"),
    ('Clarence Seedorf', "Iconic retired"),
    ('Davor Šuker', "Iconic retired"),
    ('Dennis Bergkamp', "Iconic retired"),
    ('Didier Drogba', "Iconic retired"),
    ('Diego Maradona', "Iconic retired"),
    ('Edwin van der Sar', "Iconic retired"),
    ('Emilio Butragueño', "Iconic retired"),
    ('Eusébio', "Iconic retired"),
    ('Fabio Cannavaro', "Iconic retired"),
    ('Fernando Hierro', "Iconic retired"),
    ('Fernando Torres', "Iconic retired"),
    ('Ferenc Puskás', "Iconic retired"),
    ('Franck Ribéry', "Iconic retired"),
    ('Franco Baresi', "Iconic retired"),
    ('Frank Lampard', "Iconic retired"),
    ('Francesco Totti', "Iconic retired"),
    ('Gareth Bale', "Iconic retired"),
    ('Gary Lineker', "Iconic retired"),
    ('Gennaro Gattuso', "Iconic retired"),
    ('George Best', "Iconic retired"),
    ('Gianfranco Zola', "Iconic retired"),
    ('Gianluigi Buffon', "Iconic retired"),
    ('Gerd Müller', "Iconic retired"),
    ('Hristo Stoichkov', "Iconic retired"),
    ('Hugo Sánchez', "Iconic retired"),
    ('Iker Casillas', "Iconic retired"),
    ('Ian Rush', "Iconic retired"),
    ('Jari Litmanen', "Iconic retired"),
    ('Javier Zanetti', "Iconic retired"),
    ('Jay-Jay Okocha', "Iconic retired"),
    ('Johan Cruyff', "Iconic retired"),
    ('Kaká', "Iconic retired"),
    ('Kenny Dalglish', "Iconic retired"),
    ('Lev Yashin', "Iconic retired"),
    ('Lilian Thuram', "Iconic retired"),
    ('Lothar Matthäus', "Iconic retired"),
    ('Luis Figo', "Iconic retired"),
    ('Marcel Desailly', "Iconic retired"),
    ('Marcelo', "Iconic retired"),
    ('Marco van Basten', "Iconic retired"),
    ('Miroslav Klose', "Iconic retired"),
    ('Michael Ballack', "Iconic retired"),
    ('Michael Essien', "Iconic retired"),
    ('Michael Owen', "Iconic retired"),
    ('Oliver Kahn', "Iconic retired"),
    ('Paolo Maldini', "Iconic retired"),
    ('Patrick Vieira', "Iconic retired"),
    ('Pele', "Iconic retired"),
    ('Peter Schmeichel', "Iconic retired"),
    ('Petr Čech', "Iconic retired"),
    ('Raúl', "Iconic retired"),
    ('Roberto Baggio', "Iconic retired"),
    ('Roberto Carlos', "Iconic retired"),
    ('Robin van Persie', "Iconic retired"),
    ('Ronaldinho', "Iconic retired"),
    ('Ronaldo Nazário', "Iconic retired"),
    ('Roy Keane', "Iconic retired"),
    ('Ruud Gullit', "Iconic retired"),
    ('Rui Costa', "Iconic retired"),
    ("Samuel Eto'o", "Iconic retired"),
    ('Steven Gerrard', "Iconic retired"),
    ('Thierry Henry', "Iconic retired"),
    ('Toni Kroos', "Iconic retired"),
    ('Xavi', "Iconic retired"),
    ('Zinedine Zidane', "Iconic retired"),
    ('Zlatan Ibrahimović', "Iconic retired"),
    ('Abédi Pelé', "Iconic retired"),
    ('Aleksandr Mostovoi', "Iconic retired"),
    ('Alexei Smertin', "Iconic retired"),
    ('Antonio Di Natale', "Iconic retired"),
    ('Clint Dempsey', "Iconic retired"),
    ('David Ginola', "Iconic retired"),
    ('Diego Forlán', "Iconic retired"),
    ('Dirk Kuyt', "Iconic retired"),
    ('Eden Hazard', "Iconic retired"),
    ('Harry Kewell', "Iconic retired"),
    ('Iván Córdoba', "Iconic retired"),
    ('Jamie Carragher', "Iconic retired"),
    ('Javier Mascherano', "Iconic retired"),
    ('Jean-Pierre Papin', "Iconic retired"),
    ('Joe Cole', "Iconic retired"),
    ('Jorge Campos', "Iconic retired"),
    ('Landon Donovan', "Iconic retired"),
    ('Lucio', "Iconic retired"),
    ('Mario Kempes', "Iconic retired"),
    ('Park Ji-Sung', "Iconic retired"),
    ('Rafael Márquez', "Iconic retired"),
    ('Ricardo Carvalho', "Iconic retired"),
    ('Saeed Al-Owairan', "Iconic retired"),
    ('Tomas Brolin', "Iconic retired"),
    ('Włodzimierz Smolarek', "Iconic retired"),
    ('Yaya Touré', "Iconic retired"),
]
